### ISSUE TITLE
switch to more up-to-date data source

### ISSUE THREAD

**Issue by b-vetter** [derhuerst/german-license-plate-prefixes#5]
Now after the "Kennzeichenliberalisierung" old prefixes are again useable.
That means that the current list of license plate prefixes is not up to date.

Can you update the list?
The problem is that I can't find a up to date list from the gouvernement.
This list seems to be relatively up to date.

**Comment by derhuerst** [comment]
> Now after the "Kennzeichenliberalisierung" old prefixes are again useable.

Can you elaborate? How were they unusable before?

> Can you update the list?

Sure! I will make it get updated automatically.

> The problem is that I can't find a up to date list from the gouvernement.

What about [the one linked in the readme](http://daten.berlin.de/datensaetze/kfz-kennzeichen-deutschland)? It's from 2016 though.

**Comment by derhuerst** [comment]
Re-ran the build script and published as `german-license-plate-prefixes@2.0.0`. Not sure if the data is more up-to-date though.

**Comment by b-vetter** [comment]
> > Now after the "Kennzeichenliberalisierung" old prefixes are again useable.
> 
> Can you elaborate? How were they unusable before?

Yes if I understand it right the prefixes was unusable until the "Kennzeichenliberalisierung" in 2012. 

> > The problem is that I can't find a up to date list from the gouvernement.
> 
> What about [the one linked in the readme](http://daten.berlin.de/datensaetze/kfz-kennzeichen-deutschland)? It's from 2016 though.

No, this list is still outdated. Please don't ask me why. 😄 
I can't find the new prefixes inside the list.

Here can you find the new prefixes: https://de.wikipedia.org/wiki/Kennzeichenliberalisierung

**Comment by derhuerst** [comment]
Can you ~comment on the dataset page~ contact the person responsible for the data source?

**Comment by b-vetter** [comment]
Okay, I've contacted Mr. Both. 📬 I come back to you if I've got a response from him.

**Comment by b-vetter** [comment]
I have got new information from the berlin open data team:
> ...obwohl mehrere Menschen aus verschiedenen Einrichtungen gesucht haben, konnte
bisher kein aktueller Datensatz in der Berliner Verwaltung aufgetrieben werden...

But this list should contain the recent plate status: https://gdz.bkg.bund.de/index.php/default/kfz-kennzeichen-1-250-000-kfz250.html
Its maybe not quite update to date but it is more up to date then the current list.

**Comment by derhuerst** [comment]
> But this list should contain the recent plate status: https://gdz.bkg.bund.de/index.php/default/kfz-kennzeichen-1-250-000-kfz250.html

Let's switch to that one! Do you want to submit a PR that changes the build script to make use of it?

The data has a proprietary license, so a major version bump would be appropriate.

**Comment by derhuerst** [comment]
Can you submit another PR that updates `readme.md`, `license` and the `license` field in `package.json`?
